name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: 33.0.2
        ndk-version: 25.2.9519653

    - name: Grant gradlew permission
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug \
          --stacktrace \
          --info \
          --no-daemon \
          -Dorg.gradle.parallel=false