name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Android SDK API 34
      run: |
        yes | sdkmanager "platforms;android-34" "build-tools;34.0.0"

    - name: Grant gradlew permission
      run: chmod +x gradlew
      
    - name: Check Java version
      run: java -version  

    - name: Build with Gradle
      run: |        
        ./gradlew clean build
        ./gradlew app:dependencies
        ./gradlew assembleDebug \
          --stacktrace \
          --info \
          --no-daemon \
          -Dorg.gradle.parallel=false