name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Android SDK API 34
      run: |
        yes | sdkmanager "platforms;android-34" "build-tools;34.0.0"

    - name: Grant gradlew permission
      run: chmod +x gradlew
      
    - name: Check Java version
      run: java -version  

    - name: Build with Gradle and Archive
      run: |        
        ./gradlew clean build
        ./gradlew app:dependencies
        ./gradlew assembleRelease \
          --stacktrace \
          --info \
          --no-daemon \
          -Dorg.gradle.parallel=false
    
    - name: Set TAG_NAME
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Upload APK
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: app/build/outputs/apk/release/app-release-unsigned.apk